spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: ${SPRING_DATASOURCE_URL:}
    username: ${SPRING_DATASOURCE_USERNAME:}
    password: ${SPRING_DATASOURCE_PASSWORD:}

auth:
  jwt:
    secret: ${AUTH_JWT_SECRET:}
    access-token-expiration-seconds: ${AUTH_JWT_ACCESS_TOKEN_EXPIRATION_SECONDS:3600}
    refresh-token-expiration-seconds: ${AUTH_JWT_REFRESH_TOKEN_EXPIRATION_SECONDS:1209600}
